alias reports="cd $HOME/Projects/FincaReports/finca_upload_side/ && npm start"
alias esp32-export=". $HOME/Documents/Varios/esp-idf/export.sh"
alias code="code --enable-features=UseOzonePlatform --ozone-platform=wayland  --log debug --log debug --log debug --log debug"
alias firefox="firefox --ozone-platform=wayland"
alias vi="nvim"
alias vim="nvim"
alias y="yazi"
alias ls="lsd"
alias neofetch="neofetch --backend chafa --source ~/Documents/Varios/AsciiArt/bridget_art.jpg"
alias flutterEmulator="$HOME/Android/Sdk/emulator/emulator -avd flutter_emulator"
alias fastfetch="fastfetch --config groups"
alias flatpak0-update="~/ShellFiles/flatpak-update.sh"
alias deno-tauri-run="WEBKIT_DISABLE_DMABUF_RENDERER=1 deno task tauri dev"
alias nvi = "nvim ."
